In [1]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
import scipy

In [2]:
df = pd.read_csv("../artifacts/prepare/train.tsv",sep = "\t",names=["id","label","text"],encoding="utf8")

In [3]:
df.head()

id  label                                               text
0   4186249      1  ,Searching and capturing a character using reg...
1     54312      0  , <p>Yes, of course there is :-) object orient...
2   7956164      0  , <p>Try waiting for window's <code>load</code...
3   3289313      0  , <p>Assuming that's VB.Net, you need to escap...
4  10314039      0  , <p>Usually when the add-to-cart button does ...

In [4]:
train_words = df.text.str.lower().values.astype("U")

In [7]:
train_words[:2]

array([',searching and capturing a character using regular expressions python <p>while going through one of the problems in <a href="http://www.pythonchallenge.com/" rel="nofollow">python challenge</a>, i am trying to solve it as follows:</p> <p>read the input in a text file with characters as follows:</p> <pre><code>dqheabsamljtmaokmnslzivmenfxqdatqijitwtychyemwqtnxbblxwzngmdqhhxnlhfeyvzxmhsxzd bebaxeapgqpttvqrvxhpeoutisttpdeeugfgmdkkqceyjusuigrogfypzkqgvccdbkrcywhflvpzdmek myupxvgtgsvwgrybkonbeghqhuxhhnyjfwsftfaiwtaombzescsosumwpssjcpllblspigffdlpzzmkz jarrjufhgxdrzywwosrblprasvrupzlaubtdhgzqtvzovhevstbhpitdlluljvvwrwvhpnvzewvyhmps kmvcdehzfzxtwocgvakhhcnozrsbwsiehpenfjarjlwwcvkftlhuvsjcziyfpcyrojxopkxhvucqcuge luwlbcmqpwdvupubrrjzhfexhxsbvljqjvvfegruwrshpekujcpmpisrv....... </code></pre> <p>what i need is to go through this text file and pick all lower case letters that are enclosed by only three upper-case letters on each side.</p> <p>the python script that i wrote to do the above 

In [5]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
bag_of_words = CountVectorizer(stop_words="english",max_features=3000,ngram_range=(1,2))
bag_of_words.fit(train_words)
# print(bag_of_words.vocabulary_)
train_word_binary_metrix = bag_of_words.transform(train_words)

In [6]:
train_word_binary_metrix.shape

(19857, 3000)

In [8]:
type(train_word_binary_metrix)

scipy.sparse.csr.csr_matrix

In [9]:
train_word_binary_metrix

<19857x3000 sparse matrix of type '<class 'numpy.int64'>'
	with 815493 stored elements in Compressed Sparse Row format>

In [10]:
import scipy
id_metrix = scipy.sparse.csr_matrix(df.id.astype(np.int64)).T
label_metrix = scipy.sparse.csr_matrix(df.label.astype(np.int64)).T

In [11]:
print(id_metrix.toarray())

[[ 4186249]
 [   54312]
 [ 7956164]
 ...
 [34690192]
 [26905220]
 [ 1518781]]


In [12]:
print(label_metrix.toarray())

[[1]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [13]:
out = scipy.sparse.hstack([id_metrix,label_metrix,train_word_binary_metrix],format = "csr")

In [14]:
out.shape

(19857, 3002)

In [18]:
print(out[:,1].toarray())

[[1]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [19]:
print(np.squeeze(out[:,1].toarray()))

[1 0 0 ... 0 0 0]


In [24]:
out[:,2:].toarray().shape

(19857, 3000)

In [20]:
print(out)

  (0, 0)	4186249
  (0, 1)	1
  (0, 349)	1
  (0, 414)	1
  (0, 418)	3
  (0, 450)	1
  (0, 451)	2
  (0, 491)	1
  (0, 492)	1
  (0, 498)	6
  (0, 534)	1
  (0, 558)	3
  (0, 600)	1
  (0, 613)	1
  (0, 631)	1
  (0, 727)	1
  (0, 812)	1
  (0, 879)	1
  (0, 880)	1
  (0, 962)	2
  (0, 993)	1
  (0, 1023)	2
  (0, 1024)	1
  (0, 1062)	4
  (0, 1105)	3
  :	:
  (19856, 1352)	1
  (19856, 1479)	1
  (19856, 1480)	1
  (19856, 1505)	2
  (19856, 1575)	1
  (19856, 1786)	1
  (19856, 1787)	1
  (19856, 1820)	1
  (19856, 1821)	1
  (19856, 1870)	2
  (19856, 1874)	2
  (19856, 1876)	2
  (19856, 2250)	2
  (19856, 2251)	2
  (19856, 2401)	1
  (19856, 2508)	1
  (19856, 2509)	1
  (19856, 2562)	2
  (19856, 2659)	1
  (19856, 2746)	1
  (19856, 2806)	1
  (19856, 2808)	1
  (19856, 2936)	1
  (19856, 2937)	1
  (19856, 2970)	2


In [19]:
print(out.toarray())

[[ 4186249        1        0 ...        0        0        0]
 [   54312        0        0 ...        0        0        0]
 [ 7956164        0        0 ...        0        0        0]
 ...
 [40359412        0        0 ...        0        0        0]
 [34690192        0        0 ...        0        0        0]
 [26905220        0        0 ...        0        0        0]]


In [19]:
import scipy.sparse as sparse


In [ ]:
id = sparse.csr

In [14]:
#example
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
'This is the first document.',
'This document is the second document.',
'And this is the third one.',
'Is this the first document?',
 ]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [16]:
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [21]:
y = X.toarray()

In [23]:
z = sparse.csc_matrix(y)

In [24]:
print(z)

  (2, 0)	1
  (0, 1)	1
  (1, 1)	2
  (3, 1)	1
  (0, 2)	1
  (3, 2)	1
  (0, 3)	1
  (1, 3)	1
  (2, 3)	1
  (3, 3)	1
  (2, 4)	1
  (1, 5)	1
  (0, 6)	1
  (1, 6)	1
  (2, 6)	1
  (3, 6)	1
  (2, 7)	1
  (0, 8)	1
  (1, 8)	1
  (2, 8)	1
  (3, 8)	1
